
index:
  path: /
  controller: App\Controller\DefaultController::index

first_step:
  path: /first-step
  controller: App\Controller\PersonController::firstStep

second_step:
  path: /second-step
  controller: App\Controller\PersonController::secondStep

third_step:
  path: /third-step
  controller: App\Controller\PersonController::thirdStep

completed:
  path: /completed
  controller: App\Controller\PersonController::completed