
index:
  path: /
  controller: App\Controller\DefaultController::index

form_person:
  path: /form/{step}
  controller: App\Controller\PersonController::form

completed:
  path: /completed
  controller: App\Controller\PersonController::completed